// Async fetch info
export const RECEIVE_BOOK = 'RECEIVE_BOOK';
export const CLEAR_GALLERY_BOOKS = 'CLEAR_GALLERY_BOOKS';
export const RECEIVE_POPULAR_BOOKS = 'RECEIVE_POPULAR_BOOKS';
export const RECEIVE_NEWEST_BOOKS = 'RECEIVE_POPULAR_BOOKS';
export const LIKE_CHAPTER = 'LIKE_CHAPTER';
