export const RECEIVE_IMAGE = 'RECEIVE_IMAGE';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';
export const UPLOAD_DESCRIPTION = 'UPLOAD_DESCRIPTION';
export const UPLOAD_TITLE = 'UPLOAD_TITLE';
