export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
export const RECEIVE_REGISTER = 'RECEIVE_REGISTER';
export const INIT_REGISTER = 'INIT_REGISTER';
export const RECEIVE_LOGOUT = 'RECEIVE_LOGOUT';
export const RECEIVE_CUREENT_USER = 'RECEIVE_CUREENT_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const USER_COLLECTION_ERROR = 'USER_COLLECTION_ERROR';
export const USER_FAVORATE_ERROR = 'USER_FAVORATE_ERROR';
