export const RECEIVE_USER_COLLECTIONS = 'RECEIVE_USER_COLLECTIONS';
export const RECEIVE_FAVORATES = 'RECEIVE_FAVORATES';
export const TOGGLE_USER_CENTER_TAB = 'TOGGLE_USER_CENTER_TAB';
export const TO_FAVORATES = 'TO_FAVORATES';
export const TO_COLLECTIONS = 'TO_COLLECTIONS';
